repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: golangci-lint
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .vscode
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: go-unit-tests
        name: go unit tests
        entry: go test ./...
        pass_filenames: false
        language: golang
        types: [go]
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: ["dockerfile"]
        entry: hadolint
