repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: golangci-lint
      - id: go-mod-tidy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .vscode
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # v1.7.12
    hooks:
      - id: actionlint

  - repo: local
    hooks:
      - id: go-mod-verify
        name: go mod verify
        entry: go mod verify
        pass_filenames: false
        language: golang
        types: [go]
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: ["dockerfile"]
        entry: hadolint
